### ISSUE TITLE
[FEATURE REQUEST] Up/Down Camera Name Recognition

### ISSUE THREAD

**Issue by Shaische** [openpnp/openpnp#1314]
# Feature Request
## Describe the Feature
Have OpenPNP automatically recognize and select an Upward and Downward looking camera by name, for Device selection if found.

## How Will It Look?
Manufacturer will name the camera. Should be one word such as Upward or Downward without spaces and not be case sensitive. For backup option, possibly have an input text field in OpenPNP to determine exact name to look for in case a manufacturer produces a camera with spelling errors. This field can be auto-populated during OpenPNP install with "Downward" or "Upward".

## Why Do We Need It?
Camera names vary and you have to guess which camera you've selected and check it. This will pave the way to having manufacturers start offering cameras with a pre-defined name.

## Provide Examples
None found.

**Comment by vonnieda** [comment]
All: I think this is actually not a problem if the cameras have unique names. Does anyone have cameras in hand that have unique names that can test?

The root issue here is that we have been unable to get cameras with unique names or serial numbers. openpnp-capture does look at these properties, but since all the cameras on the market use the same name (per model) and no serial number there is nothing unique to match on. 

If someone has cameras with unique names and that name is not ending up in the unique ID that OpenPnP stores, that's a bug in openpnp-capture that would be worth fixing.
