### ISSUE TITLE
ReferenceStripFeeder vision sometimes fails to find the next hole

### ISSUE THREAD

**Issue by readerror67** [openpnp/openpnp#177]
Ended up putting some breakpoints in place if the error took place, ended up collecting a screenshot and the debug values from Eclipse:

![feedererror_2](https://cloud.githubusercontent.com/assets/1146686/11697708/e115d5ac-9e88-11e5-82c5-2f2874e8709b.png)
(Sorry about the picture, pasting seemed to really mess with Githubs formatting and it was unreadable) 

Screenshot:
![feedererror_1](https://cloud.githubusercontent.com/assets/1146686/11697508/de9c3e0c-9e87-11e5-8589-97e074b033ec.png)

**Comment by readerror67** [comment]
Adding pictures with light on and off.

On:
![opencvcamera_2015-12-09_15 09 57 000](https://cloud.githubusercontent.com/assets/1146686/11697951/514f6152-9e8a-11e5-9b41-e398c4d88eef.png)

Off:
![opencvcamera_2015-12-09_15 32 46 962](https://cloud.githubusercontent.com/assets/1146686/11697954/599b058c-9e8a-11e5-8a93-081033d3317b.png)

**Comment by vonnieda** [comment]
Note to myself so it doesn't get forgotten: This data was collected in trying to track down why ReferenceStripFeeder vision was failing sometimes. I noted the pictures look somewhat out of focus. @readerror67 followed up saying that eventually the expected position was getting so far out of whack due to the line being off at a distance that it wasn't finding the hole.

One solution is to recalculate the line for each feed by using the last found vision hole and either the first, second or next more recent vision location.

**Comment by vonnieda** [comment]
This is now fixed, or at least improved. The vision code now uses the last located hole along with the first hole to calculate the line to follow and it results in much  better following at the extents of strips.

Fixed in 7ee64b0624ec89ad5bd13fe3e5e2c54f713d5191
