### ISSUE TITLE
Job stops with "Bottom vision only implemented ..."

### ISSUE THREAD

**Issue by ldpgh** [openpnp/openpnp#257]
While starting a Job at the first part a "PartError" message pops up with the message ... "Bottom vision only implemented for Up looking cameras".
Though OpenCV camera (looking DOWN) is attached and it's disabled ... running the job without using the vision system.
Could track the root cause down to  OpenCvVisionProvider.Java:235   with ImageCamera:"Up" ... 
![camera_bottom_vision__debug_breakpoint](https://cloud.githubusercontent.com/assets/13517069/14669225/33d3e99c-06e8-11e6-914d-78a1adda4663.JPG)
but in the camera-tab image camera has property "Looking"="Down" assigned.
![camera_bottom_vision__gui_camera](https://cloud.githubusercontent.com/assets/13517069/14669365/cc6f21c6-06e8-11e6-8dc0-754e980a67a3.JPG)

**Comment by vonnieda** [comment]
The reason you are seeing this error is because you have a non-head attached camera (Zoom). It's a bug, since it should be ignored if it's not set to Up looking, but you can get around it just by removing that extra camera that you aren't using.

This bug is fixed in the new bottom vision code that will be released soon.

Note to self: Close this when #104 is complete.

**Comment by vonnieda** [comment]
Fixed in #104.
