### ISSUE TITLE
RefDes broken

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#324]
RefDes and other ID need to be uniq. It's imperative that there are unique and industry convention.
Just seen it's possible to import board twice and it builds doubled RefDes.
The Tracing, the layout Software, all surrounding docs and software relay that RefDes (U1, R2 ...)
is unique.

**Comment by tracklogic** [comment]
I've come across this with the feeders too... when you add a new feeder i think it should be given a better name than the class name (i.e. if i add a feeder of class type ReferenceAutoMountableFeeder, it seems to label it ReferenceAutoMountableFeeder rather than something like FeederX - where X is the next free id?). Probably needs a bit of thought though.
