### ISSUE TITLE
future (threading) abstraction makes timing failure.

### ISSUE THREAD

**Issue by cri-s** [openpnp/openpnp#338]

**Comment by cri-s** [comment]
Severity: low.
Description:
Its normal that GUI ui have its own thread, but main thread need to be in sync  at least with motion and camera, actuators and other interfaces, otherwise delay need have extra time. As example its a fault doing camera motion using future interface and setting timer to take picture after expiration. Doing it so its not granted that camera is out of motion. Example of error source: USB reconnect.
Using futures is possible, I'm not saying is wrong and I could be wrong with my teardown of error analysis.

**Comment by vonnieda** [comment]
Please add more detail to this issue. It is not clear what feature or code you are referring to, or what the problem is. See: https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md#issues-bug-reports-and-feature-requests

If this is a feature request, please specify exactly what you are looking for. If it a bug report, please include step by instructions on how to reproduce the error.

**Comment by cri-s** [comment]
Too hard to make test case.
