### ISSUE TITLE
Gcode vacuum pump start/stop at beginning/end of a job

### ISSUE THREAD

**Issue by bzhex** [openpnp/openpnp#383]
It would be nice to have in Gcode driver some commands like "JOB_START" and "JOB_END" where user can send Gcode command for start/stop vacuum pump when job is running. I dont see why a vacuum pump should start on "ENABLE_COMMAND" for axample. If I have to do test movements, calibration etc, i do not need vacuum pump started. Also in Jog panel would be nice to have 2 buttons - START / STOP VACUUM.

**Comment by vonnieda** [comment]
@bzhex There are PUMP_ON and PUMP_OFF commands that are sent when the pump is needed. Will these suit your use case? https://github.com/openpnp/openpnp/wiki/GcodeDriver:-Command-Reference#pump_on_command. Using these commands guarantees the pump is only turned on when it's needed.

For testing the pump, it's best to just use the test pick and discard buttons. It's difficult to have a specific vacuum on and vacuum off command since these are very different depending on machine configuration.

**Comment by bzhex** [comment]
Missed that commands. Worked great.
