### ISSUE TITLE
CamTransform sometimes returns NaN on Z axis

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#431]
This happens when you move past a valid angle for the motor, i.e. when a nozzle is further down than it should go. I can't remember the mathematical reason at the moment but it should be clear when looking at the code. Need to protect against this as once it happens it's hard to recover from. Probably just need to have a floor value for the nozzle.

**Comment by cri-s** [comment]
Please don't remove NaN, there have some use, example manual nozzle change, or with configuration using
external rotation station and other uses. I know you have already made some works for this.
Instead of banning NaN from location where you force bounding function using location with catch/try 
why not just catch the error inside gcode driver.
NaN can be specified inside machine.xml, not GUI, as opposed to null.
Further on Head/Nozzle you already have exchanged NaN with actual position or null i think.
After this lines, add the code to check floating point errors.
 // Only give a command when move is necessary
            if (haveToMove) {
// new float validity check
	if (Double.isNaN(x)||Double.isInifinite(x)) { /* raise exception */ }
	if (Double.isNaN(y)||Double.isInifinite(y))  { /* raise exception */ }
	if (Double.isNaN(z)||Double.isInifinite(z)) { /* raise exception */ }
	if (Double.isNaN(rotation)||Double.isInifinite(rotation))  { /* raise exception */ }
// everything ok.
