### ISSUE TITLE
NamedCsvImporter Improvements

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#444]
The NamedCsvImporter needs some cleanup and improvements. Daniel from IRC reports that an Altium exported file fails to load. The files are attached below along with some comments from the reporter.

I think we should probably take a close look at rewriting the importer from scratch. The code is very rough and there are a lot of hardcoded values and difficult to understand code paths. I think the whole thing could be simplified greatly with the following ideas in mind:

* Importing of delimited files in general. Allow user to specify delimiter.
* Ignore non-matching lines, like the preamble visible in the attached files.
* Allow user to specify field names and formats for each of the required fields.
* The import dialog should save it's settings between sessions.
* Stretch Goal: Dropdown with some common file format profiles to autofill the dialog.

It may make sense for this to be a new importer caller DelimitedTextImporter.

Notes below:

> attached you will find my recreated files.
> One as a .csv and one text file, as i can export both.
> Note that my values are with a comma and not a dot. 

> I tried a couple of more files, and it seems like my .csv has problems. 
> The importer works fine if i copy and paste the content into a .txt file and delete the overhead and fix the field-names. 
> 
> All values are imported correctly, with reference to values having a comma instead of a dot. 
> My Values: 2,500mm
> Example Values: 2.500mm
> 

[csv_altium.txt](https://github.com/openpnp/openpnp/files/756285/csv_altium.txt)

[altium.txt](https://github.com/openpnp/openpnp/files/756287/altium.txt)

**Comment by cri-s** [comment]
simplified greatly with the following ideas in mind:
Delimiters are automatically detected.
Non matching lines are automatically ignored.
It imports CSV files, not Excel files. 
The second file is Exel file, it have excel ""delimiter"" instead of CSV "delimiter" .
Some limits was chosen, format specs need to be within the first 10 lines, and it need to be present 6 valid fields in order file is imported. In this file format specs is on the eleven line. Its possible to change this, changing this for, its increases wrong import risk too.
for (int i = 0; i++ < 10 && (line = reader.readLine()) != null;) {

**Comment by vonnieda** [comment]
Note that work done in #461 should resolve the Altium issue.

**Comment by vonnieda** [comment]
Recent changes have improved this enough. If additional changes are needed, new issues can be opened.
