### ISSUE TITLE
EOL at EOF in xml files

### ISSUE THREAD

**Issue by ticso24** [openpnp/openpnp#730]
# Read This First

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
OpenPnP saves the  xml files without line termination at end of file.
The issue is that I often edit them with vi, which adds an EOL to the end and this creates additional difference, when I manage the files in git.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
-----------------------------------------------------------------------

# Feature Request
## Describe the Feature
I like to have OpenPnP to write the files with usual end of line termination.
It is not a big thing, but somehow bugs me.

## Why Do We Need It?
It is nothing we really need and it maybe is just a personal thing, but I don't think the change would hurt anyone else and maybe I'm not alone.

**Comment by vonnieda** [comment]
Agreed - would be a good fix. Might end up being surprisingly hard, since we use a third party library for this - but certainly worth looking in to.

**Comment by pfried** [comment]
Only for reference, POSIX standard should have a newline at the end of a file:
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

See https://stackoverflow.com/questions/1050640/vim-disable-automatic-newline-at-end-of-file for an alternative "solution" of changing vi/vim settings.

The encoding should be fairly easy since you could just write before closing. The bigger question is if it confuses the decoder which I guess doesnt.

**Comment by vonnieda** [comment]
Fixed in above commit.
