### ISSUE TITLE
Machine should move to home after a job is complete.

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#76]
See this discussion: https://groups.google.com/d/msgid/openpnp/c13aed63-840f-4512-9009-3c603434d7eb%40googlegroups.com?utm_medium=email&utm_source=footer

More discussion: https://groups.google.com/forum/#!msg/openpnp/3wFHiqpCbPo/pelK_s72EwAJ

**Updated Plan**:
* Add a Park location (x, y, z, c) to machine configuration, probably at head, although have to consider offsets and which tool we actually "Park". Probably best to just use default nozzle.
* Move to Park location after job completion.
* Add Park to Machine menu.
* Retain the existing Zero commands in the jog controls.

**Comment by FlyingLotus1983** [comment]
Just leaving a note here to my future self that this will be required for FirePIck Delta to home properly.. If it doesn't return to x=0,y=0, then the carbon arms may collide with the pulleys or bearing blocks.  Moving the machine to 0x0 after a job pretty much eliminates this.  I'm actually not sure where the machine goes at the end of a job as I've not made it that far yet.. but if it's 0,0, home or otherwise, we're ok.

**Comment by vonnieda** [comment]
Right now the nozzle just returns to safe z after the last part is placed,
and for all intents and purposes safe z is 0. So when a job completes the
nozzle will above the last part placed at z = 0.

**Comment by vonnieda** [comment]
Instead of adding another thing to config I think we should just Safe-Z and then Home after a job completes.

**Comment by vonnieda** [comment]
In addition to moving to home, if there is a part on the nozzle(s) we should first dump it in the trash bin. #102
