### ISSUE TITLE
Unsafe XY Move During Bottom Vision Test

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp#824]
User reports that the nozzle moves in Z during an XY transit from Park to Test Alignment: https://groups.google.com/d/msgid/openpnp/2e4381cf-8054-47d5-ae2c-a8f3882001ec%40googlegroups.com?utm_medium=email&utm_source=footer

I spent some time trying to reproduce this and I'm not sure I was able to. I need to try again.

Notes, machine.xml, and trimmed log attached.

[NOTES.txt](https://github.com/openpnp/openpnp/files/3101620/NOTES.txt)
[OpenPnP.log](https://github.com/openpnp/openpnp/files/3101621/OpenPnP.log)
[machine.txt](https://github.com/openpnp/openpnp/files/3101622/machine.txt)

**Comment by markmaker** [comment]
Like @tonyluken confirmed in the linked conversation, this is related to #647. It was made very unlikely with @tonyluken's #1001 and is completely fixed by using new TinyG firmware and proper M400 usage.

All about this, including the caveats and risks of upgrading a TinyG firmware in general, here:
https://makr.zone/tinyg-new-g-code-commands-for-openpnp-use/577/

After flashing new firmware [Issues & Solutions](https://github.com/openpnp/openpnp/wiki/Issues-and-Solutions) can configure TinyG commands and options accordingly.
