### ISSUE TITLE
Z offsets, Safe Heights and other "height" issues need complete overall.

### ISSUE THREAD

**Issue by wiegleyj** [openpnp/openpnp#850]
# Read This First
To submit an issue for OpenPnP you must use this template or it will be deleted. Please fill out either the Problem Report or Feature Request section below and delete the other section.

-----------------------------------------------------------------------

# Problem Report
## Describe the Issue
Use of Z offsets and safe heights in this program is completely nonsensical.

## Steps to Reproduce
Just try to use/understand any safe height or Z offset in any meaningful way.
For Instance: With the nozzle wizard, touch a nozzle tip to a surface, and capture the nozzle offsets. Now, move the camera over the mark with proper focus height and calculate the other wizard values.

Great. Now ask the nozzle to move to the camera position. The Z descends first. Nozzle tip touches the surface and THEN the machine moves the X/Y so the camera is over it. Great you just ruined your nozzle/surface because you dragged the nozzle across it due to descending to Z first. Also now, your park position is with the nozzle tip touching the surface as well. If you were to move over/across a board with this you'd shear off the nozzle.

In *every* *single* move you should be moving to a fixed safe height first! then moving to the proper X/Y location and then moving down to the desired final point.

Also, when nozzle tips change the length of the nozzle tip could be different. The length of the nozzle tip/nozzle should be stored with the nozzle tip, not the nozzle.

## Expected Result
Descent movements that protects the head and nozzle from collisions

## Actual Result
Dragged nozzle on surface.

## Notes, Log Files, Screen Captures, Videos, etc. to Show the Issue
heights:

You should have a machine safe height. A height at which no matter what head/nozzle/tip is selected there will be no collisions with objects on the bed. This should relative to the machine coordinates.

You should have an inspection height for each camera on a head. This is the height above any coordinate system that the camera will be in focus. If you select a board and visualize/inspect any point the board will be in focus. If you move above a feeder position the height should be relative to the feeder and the feeder part would be in focus.

Nozzles/Tip combinations should have a calculated length so that if you move to (0,0,0) above a board the nozzle just touches the board surface. (0,0,0) relative to the bed should just touch the bed.

I think there may be some way to adjust all these Z offsets to get this behavior but bugger me if I can figure it out. Maybe it's in the board/feeders and they are somehow configured "below" the bed conceptually.

-----------------------------------------------------------------------

**Comment by vonnieda** [comment]
Hi @wiegleyj,

It sounds like you are experiencing https://github.com/openpnp/openpnp/wiki/FAQ#my-nozzle-moves-in-z-when-the-camera-is-moved, and possibly have set your safe-z values to incorrect values while trying to debug the above. In almost all cases the safe-z values on Nozzle, Camera, Actuator, etc. will remain 0. Head offset Z is also usually 0 in most cases, although this can be modified for more advanced behavior.

There is no concept of a bed in OpenPnP, and that is by design. Most hobby pick and place machines have objects at different heights, so there is no one "correct" value. It is up to the user to select a proper safe-z value for their machine, and you can, but as I said, most people just use 0 and set up their motion controller so that 0 means all the way up. Not everyone has the ability to modify their motion controller to their preference, so having this flexibility in OpenPnP helps some folks.

In addition, the ability to move in X/Y while something is lowered in Z is also by design. This is required by drag feeders, and is used as an optimization by some of the vision algorithms.

In general, every move in OpenPnP starts with a move of all head objects to safe Z. The only ones that don't are the ones that specifically require it, as mentioned above. 


Finally, I want to ask that you deeply consider the tone of your post and it's effect on it's intended recipient.

I have now spent 30 minutes of my Friday night, after a full day of work, reading, understanding, and responding to your rude and sarcastic message. I have provided you free support, on free software, which I spend thousands of hours and dollars writing and supporting.

Everything you have described above is a misunderstanding of the available options, and you could have simply asked a polite question and received a polite answer. Instead you posted this.

If you can't be polite when interacting with this project, you will be blocked. This is the only warning you'll receive.

If you do decide you can be polite, please feel free to ask further questions and I will be happy to help you get your machine up and running. You can also ask on the discussion group at https://groups.google.com/forum/#!forum/openpnp where others may also help. The same rule applies there.

Thanks,
Jason
